### PR TITLE
Implement index

### LINKED ISSUE #94: Failing CRAN check
The package has an error on CRAN, and we have until 2024-08-29 to fix it: https://cran.r-project.org/web/checks/check_results_tidytuesdayR.html

It looks to me like the test might have ran when there was an issue. We can probably deal with almost all examples using [@examplesIf](https://r-pkgs.org/man.html#sec-man-examples-dependencies-conditional-execution), probably with a basic `interactive()`.

### LINKED ISSUE #95: Rely entirely on an index file
I'd like to expand on the general idea from `tt_data_type.csv`, and get (almost) *all* data from that file (or, likely, a file in a slightly different location, for consistency in an updating repo structure and to allow the tt repo to support both the old version of the package and the new version, at least to some degree, as we make the transition). I think you're already really close, but the piece I want to specifically add (while sorting through to see if there's anything else) is a path to each dataset file. That way we can restructure the tt repo without breaking tidytuesdayR.

The "almost" is because I think it still makes sense (at least right now) to expect a readme.md per dataset, and of course the datasets themselves will come from the specified locations. But the readme.md should be used only for display in the viewer; we shouldn't have to parse it for information, since that information can/should be parsed in the tt repo itself.

I intend to implement this, but I welcome suggestions/caveats!

### PR DESCRIPTION
**Pull request by jonthegeek**
Refactor to make CRAN happier and to add 100% test coverage.

Closes #94.

### CODE REVIEW

**Review by thebioengineer — APPROVED** [review]
thanks @jonthegeek. Looks like this one is mainly styling changes, both code, and wrapping the example code in if interactives? Is that now what CRAN accepts?

**Comment by jonthegeek** [comment]
@thebioengineer Check the required workflows. They're out-of-date, so it's impossible to succeed.
I'll mark this ready for review in a bit!

**Comment by jonthegeek** [comment]
I implemented more testing. I want to hit 100% before I start changing things for #95, so I'll have another round of changes after work, and then the actual implementation of a slightly new system (relying more on tidytuesday to supply metadata, rather than figuring it out ourselves here; that way the structure of the tidytuesday repo can change as long as the supplied metadata still works for this package).

**Comment by jonthegeek** [comment]
@thebioengineer Let's get this one merged! It can't currently pass checks, because GitHub is looking for actions that no longer exist. Can you update the branch protection rules to remove these:

- macOS-latest (devel)
- macOS-latest (release) 
- ubuntu-16.04 (release)

And then (re)add these:
- pkgdown
- test-coverage
- ubuntu-latest (release)
- macos-latest (release)

I don't think we should put the other, more-specific checks into the "required" bucket. It's good for us to get alerts if those fail, but we don't need to block PRs when they do, IMO.

**Comment by thebioengineer** [comment]
> @thebioengineer Let's get this one merged! It can't currently pass checks, because GitHub is looking for actions that no longer exist. Can you update the branch protection rules to remove these:
> 
> * macOS-latest (devel)
> * macOS-latest (release)
> * ubuntu-16.04 (release)
> 
> And then (re)add these:
> 
> * pkgdown
> * test-coverage
> * ubuntu-latest (release)
> * macos-latest (release)
> 
> I don't think we should put the other, more-specific checks into the "required" bucket. It's good for us to get alerts if those fail, but we don't need to block PRs when they do, IMO.

wouldn't that just be removing/updating the actions, not branch protection? TBH, the code for the actions is pretty old, so could probably use a wiping/reset

**Comment by jonthegeek** [comment]
The "required" notes are ones that you have set in branch protection. I already updated the actions in this PR, but I can't do that last step.

**Pull request merged**
